Application:
  type: object
  properties:
    id:
      type: string
      format: uuid
      description: Unique identifier for the application
    name:
      type: string
      description: Name of the application
    slug:
      type: string
      description: URL-friendly identifier for the application
    description:
      type: string
      description: Description of the application
    type_id:
      type: string
      format: uuid
      description: ID of the application type
    approver_group_id:
      type: string
      format: uuid
      description: ID of the group that approves application access requests
    created_at:
      type: string
      format: date-time
      description: Timestamp when the application was created
    updated_at:
      type: string
      format: date-time
      description: Timestamp when the application was last updated
    deleted_at:
      type: string
      format: date-time
      description: Timestamp when the application was deleted, if applicable
    metadata:
      type: object
      additionalProperties: true
      description: Additional metadata for the application
  required:
    - id
    - name
    - slug
    - type_id
    - created_at
    - updated_at

ApplicationType:
  type: object
  properties:
    id:
      type: string
      format: uuid
      description: Unique identifier for the application type
    name:
      type: string
      description: Name of the application type
    slug:
      type: string
      description: URL-friendly identifier for the application type
    description:
      type: string
      description: Description of the application type
    logo_url:
      type: string
      format: uri
      description: URL to the logo image for this application type
    created_at:
      type: string
      format: date-time
      description: Timestamp when the application type was created
    updated_at:
      type: string
      format: date-time
      description: Timestamp when the application type was last updated
    deleted_at:
      type: string
      format: date-time
      description: Timestamp when the application type was deleted, if applicable
  required:
    - id
    - name
    - slug
    - description
    - created_at
    - updated_at

ApplicationWithType:
  type: object
  allOf:
    - $ref: '#/Application'
    - type: object
      properties:
        type:
          $ref: '#/ApplicationType'

ApplicationCreateRequest:
  type: object
  properties:
    name:
      type: string
      description: Name of the application
      examples: ["My Service"]
    type_id:
      type: string
      format: uuid
      description: ID of the application type
      examples: ["3fa85f64-5717-4562-b3fc-2c963f66afa6"]
    description:
      type: string
      description: Description of the application
    slug:
      type: string
      description: Custom slug for the application (optional)
    approver_group_id:
      type: string
      format: uuid
      description: ID of the group that approves application access requests (if needed)
    metadata:
      type: object
      additionalProperties: true
      description: Additional metadata for the application
  required:
    - name
    - type_id

ApplicationUpdateRequest:
  type: object
  properties:
    name:
      type: string
      description: Updated name of the application
    description:
      type: string
      description: Updated description of the application
    type_id:
      type: string
      format: uuid
      description: Updated ID of the application type
    approver_group_id:
      type: string
      format: uuid
      description: Updated ID of the group that approves application access requests
    metadata:
      type: object
      additionalProperties: true
      description: Updated metadata for the application

ApplicationTypeCreateRequest:
  type: object
  properties:
    name:
      type: string
      description: Name of the application type
      examples: ["Database Service"]
    slug:
      type: string
      description: URL-friendly identifier for the application type
      examples: ["database-service"]
    description:
      type: string
      description: Description of the application type
      examples: ["Database services that require access management"]
    logo_url:
      type: string
      format: uri
      description: URL to the logo image for this application type
      examples: ["https://example.com/logos/database.png"]
  required:
    - name
    - slug
    - description

ApplicationTypeUpdateRequest:
  type: object
  properties:
    name:
      type: string
      description: Updated name of the application type
    description:
      type: string
      description: Updated description of the application type
    logo_url:
      type: string
      format: uri
      description: Updated URL to the logo image for this application type
